sudo: false
language: java
jdk:
- oraclejdk8
before_install:
- git clone https://github.com/iipc/travis.git target/travis
before_script:
- export JAVA_OPTS=-Xmx1024m
- export MAVEN_OPTS=-Xmx512m
- ulimit -u 2048
script:
- target/travis/deploy-if.sh
branches:
  only:
  - master
env:
  global:
  - secure: kOUm0C3dRjgTdKBQbbJQRjD/p52OVBFZSKWxmIj0sbKuLzKf29t2ebvn6s6wCg6QxmU3f7jKGugunTM5QJEZ3jiAjlgcC51S5STit0ePQDfwzwPJPvru+9otEvBH4BHKQHvnpsflDY0i0/HJcD6kJPetCvQXSphXUQvTfFbkyNaDIqfxu7Z7ElLM9coG0ZhJCkVPulbZAjjIH2WPQIvIfsL7ZEAEyVN/EM17nkk6L575aZELVocxP6jnLGxZ4EBaBR014aEHvqfEfr0phTXKLPDMTyKFIIwew5jRcMLRWu6SdRhqO0+I48gyG3lENrfggR2a4LQZkerMMwtBfSh4VS6V4pFiFuaC/qCISK5NM08DmC7DrOi6l/7ksDus5LrIiJPvWB11Y9w8xxYHVac2hDxa7/oKv3ANYgYv+etOH4HH5wCk190XSYuqrs3oNd1ypZxGqGpBTtZ3cygtt8njiQfd24qOfaCVUeRd4yPx+/eIYRxcAqdrDI0gslMkamVo9Nm0bHnGaOxZ6A1pCsbFSIc9mrCNxHElS7bVYcSBkwz5AOntTpUsjlKtDGIPRQ97oAfS1RrJ32FcO1fElhDiKwWpIz/qgv+MD3Is+PjnAnKatb1MtVX8gvkjnBwDWWT5qcfbTq2K26+buwGNIgXJlHcW2UFjAVv+zn8djBOfsXw=
  - secure: FJ7trbK4cJx80x1BxjUf7B9s3w4pLL1mUeulFDdaljErLYigdS61QxNcXIbEqldVFCamf9CRPaXROqmP1qLZ9BvWm+14ogQPdJ/y7667FaDfxUdmNltKfSX5G4qmgOLeXLBW6IzjRRkD+OBJDhJU8jcQDmyPdFOuC6UMx2B6+vrTgpVW3U2574+eT02JP899XDsv12smthrWcKbAZ99rmXk4UmHTXrzRzBiXt+QuoO+c60fwsPJ9tZq0/d96dl47IdA1j3LU2X5f4S8hoxP0b5QzvPFi4lJfC0cHVHnoxd2NzB6RwbNBn3ZbzYLyvkBB1RgbEBCf5VqR5jX4wMgResR31FMKd3sgJyllR1D242WeYhakoIkDJBE1fwUaHzfHXICkiSZdWh9LmtVINmb24DmBeq0Td60zt/g4w0wrIplBAVpP+uLl5XvrBFvLU0E9a1dpLVDz2begzCGsdhIZlZkXvI7zACdCkZ2EeqHGVwtr2bRKTy1RvvP00oYQGrXSMMG99OpgjKSCgWjd2qd6UY4KvKMMtwrTKLiPToz7By3q79FAcANHeT0f0GTTOPubyghhiPxkNux51uu/9dpkulocR4N5qot4b+S0vtUeGaSj5CG2jJhQ7+7NN5ZMQq4nqT/Hlts4JHt89dDTJOMO2HZd0VNmWYID6hM+lV2noSg=
